### ISSUE TITLE
Join the course

### ISSUE THREAD

**Issue by vadal** [cltl/python-for-text-analysis#7]
Hello! Can I start this course now (submit assignments and get feedback)?

**Comment by ChantalvanSon** [comment]
Dear vadal,

Unfortunately, we cannot provide feedback since this is a course designed for students at the VU University of Amsterdam. You're very welcome to do the assignments anyway, of course! I can also send you the answers by e-mail, if you like. Just drop me an e-mail at cm.vanson at gmail.

Best,
Chantal
